<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Database\Seeders\ProductSeeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'id' => 1,
                'brand_id' => 101,
                'name' => 'iPhone 13 Mini',
                'slug' => 'ini-adalah-slug',
                'dimensions' => '131.5 x 64.2 x 7.7 mm',
                'display' => 'Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)',
                'os' => 'iOS 15, upgradable to iOS 15.5',
                'chipset' => 'Apple A15 Bionic (5nm)',
                'cpu' => 'Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)',
                'memory' => '128GB 4GB RAM, 256GB 4GB RAM, 512GB 4GB RAM',
                'battery' => 'Li-Ion 2438 mAh, non-removable (9.34 Wh)',
                'description' => 'iPhone 13 Mini is a slim, lightweight, and powerful Smartphone designed for the Apple iPhone. It features a 13.5-inch Super Retina XDR OLED display with HDR10 support, a 12MP primary camera, and a 7MP front camera. It has a 3.5mm headphone jack and a built-in microphone. It has a 128GB or 256GB storage option, and a 4GB or 8GB RAM option.',
                'price' => '14990000',
                'stock' => '10',
                'release_date' => now(),
                'image' => 'images/product_apple_13.jpg',
            ],
            [
                'id' => 2,
                'brand_id' => 101,
                'name' => 'iPhone 11 Pro',
                'slug' => 'ini-adalah-slug',
                'dimensions' => '144 x 71.4 x 8.1 mm',
                'display' => 'Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)',
                'os' => 'iOS 13, upgradable to iOS 15.5',
                'chipset' => 'Apple A13 Bionic (7 nm+)',
                'cpu' => 'Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)',
                'memory' => '64GB 4GB RAM, 256GB 4GB RAM, 512GB 4GB RAM',
                'battery' => 'Li-Ion 3046 mAh, non-removable (11.67 Wh)',
                'description' => 'iPhone 11 Pro is a powerful, ultra-compact Smartphone designed for the Apple iPhone. It features a 13.5-inch Super Retina XDR OLED display with HDR10 support, a 12MP primary camera, and a 7MP front camera. It has a 3.5mm headphone jack and a built-in microphone. It has a 64GB or 256GB storage option, and a 4GB or 8GB RAM option.',
                'price' => '24990000',
                'stock' => '10',
                'release_date' => now(),
                'image' => 'images/product_apple_11pro.jpg',
            ],
            [
                'id' => 3,
                'brand_id' => 101,
                'name' => 'iPhone 13',
                'slug' => 'ini-adalah-slug',
                'dimensions' => '146.7 x 71.5 x 7.7 mm',
                'display' => 'Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)',
                'os' => 'iOS 15, upgradable to iOS 15.5',
                'chipset' => 'Apple A15 Bionic (5 nm)',
                'cpu' => 'Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)',
                'memory' => '128GB 4GB RAM, 256GB 4GB RAM, 512GB 4GB RAM',
                'battery' => 'Li-Ion 3240 mAh, non-removable (12.41 Wh)',
                'description' => 'iPhone 13 is a slim, lightweight, and powerful Smartphone designed for the Apple iPhone. It features a 13.5-inch Super Retina XDR OLED display with HDR10 support, a 12MP primary camera, and a 7MP front camera. It has a 3.5mm headphone jack and a built-in microphone. It has a 128GB or 256GB storage option, and a 4GB or 8GB RAM option.',
                'price' => '19900000',
                'stock' => '10',
                'release_date' => now(),
                'image' => 'images/product_apple_13.jpg',
            ],
            [
                'id' => 4,
                'brand_id' => 101,
                'name' => 'iPhone 13 Pro',
                'slug' => 'ini-adalah-slug',
                'dimensions' => '146.7 x 71.5 x 7.7 mm',
                'display' => 'Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (HBM), 1200 nits (peak)',
                'os' => 'iOS 15, upgradable to iOS 15.5',
                'chipset' => 'Apple A15 Bionic (5 nm)',
                'cpu' => 'Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)',
                'memory' => '128GB 6GB RAM, 256GB 6GB RAM, 512GB 6GB RAM, 1TB 6GB RAM',
                'battery' => 'Li-Ion 3095 mAh, non-removable (12.11 Wh)',
                'description' => 'iPhone 13 Pro is a slim, lightweight, and powerful Smartphone designed for the Apple iPhone. It features a 13.5-inch Super Retina XDR OLED display with HDR10 support, a 12MP primary camera, and a 7MP front camera. It has a 3.5mm headphone jack and a built-in microphone. It has a 128GB or 256GB storage option, and a 4GB or 8GB RAM option.',
                'price' => '29990000',
                'stock' => '10',
                'release_date' => now(),
                'image' => 'images/product_apple_13pro.jpg',
            ],
            [
                'id' => 5,
                'brand_id' => 101,
                'name' => 'Apple Iphone 13 Pro Max',
                'slug' => 'ini-adalah-slug',
                'dimensions' => '160.8 x 78.1 x 7.7 mm',
                'display' => 'Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (HBM), 1200 nits (peak)',
                'os' => 'iOS 15, upgradable to iOS 15.5',
                'chipset' => 'Apple A15 Bionic (5 nm)',
                'cpu' => 'Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)',
                'memory' => '128GB 6GB RAM, 256GB 6GB RAM, 512GB 6GB RAM, 1TB 6GB RAM',
                'battery' => 'Li-Ion 4352 mAh, non-removable (16.75 Wh)',
                'description' => 'Apple Iphone 13 Pro Max is a slim, lightweight, and powerful Smartphone designed for the Apple iPhone. It features a 13.5-inch Super Retina XDR OLED display with HDR10 support, a 12MP primary camera, and a 7MP front camera. It has a 3.5mm headphone jack and a built-in microphone. It has a 128GB or 256GB storage option, and a 4GB or 8GB RAM option.',
                'price' => '39990000',
                'stock' => '10',
                'release_date' => now(),
                'image' => 'images/product_apple_13promax.jpg',
            ],
            [
                'id' => 6,
                'brand_id' => 101,
                'name' => 'Apple Iphone SE (2022)',
                'slug' => 'ini-adalah-slug',
                'dimensions' => '138.4 x 67.3 x 7.3 mm',
                'display' => 'Retina IPS LCD, 625 nits (typ)',
                'os' => 'iOS 15.4, upgradable to iOS 15.5',
                'chipset' => 'Apple A15 Bionic (5 nm)',
                'cpu' => 'Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)',
                'memory' => '64GB 4GB RAM, 128GB 4GB RAM, 256GB 4GB RAM',
                'battery' => 'Li-Ion 3095 mAh, non-removable (12.11 Wh)',
                'description' => 'Apple Iphone SE (2022) is a slim, lightweight, and powerful Smartphone designed for the Apple iPhone. It features a 13.5-inch Super Retina XDR OLED display with HDR10 support, a 12MP primary camera, and a 7MP front camera. It has a 3.5mm headphone jack and a built-in microphone. It has a 64GB or 256GB storage option, and a 4GB or 8GB RAM option.',
                'price' => '19990000',
                'stock' => '10',
                'release_date' => now(),
                'image' => 'images/product_apple_se2022.jpg',
            ],
            [
                'id' => 7,
                'brand_id' => 102,
                'name' => 'Infinix Note 12',
                'slug' => 'ini-adalah-slug',
                'dimensions' => '164.4 x 76.7 x 7.9 mm',
                'display' => 'AMOLED, 1000 nits (peak)',
                'os' => 'Android 11, XOS 10.6',
                'chipset' => 'MediaTek Helio G88 (12nm)',
                'cpu' => 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
                'memory' => '64GB 4GB RAM, 128GB 4GB RAM, 128GB 6GB RAM',
                'battery' => 'Li-Po 5000 mAh, non-removable',
                'description' => 'Infinix Note 12 is a slim, lightweight, and powerful Smartphone designed for the Apple iPhone. It features a 13.5-inch Super Retina XDR OLED display with HDR10 support, a 12MP primary camera, and a 7MP front camera. It has a 3.5mm headphone jack and a built-in microphone. It has a 64GB or 256GB storage option, and a 4GB or 8GB RAM option.',
                'price' => '9000000',
                'stock' => '10',
                'release_date' => now(),
                'image' => 'images/product_infinix_0Xpro.jpg',
            ],
            [
                'id' => 8,
                'brand_id' => 102,
                'name' => 'Infinix Note 11 Pro',
                'slug' => 'ini-adalah-slug',
                'dimensions' => '173.1 x 78.4 x 8.7 mm',
                'display' => 'IPS LCD, 120Hz',
                'os' => 'Android 11, XOS 10',
                'chipset' => 'Mediatek Helio G96 (12 nm)',
                'cpu' => 'Octa-core (2x2.05 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)',
                'memory' => '128GB 4GB RAM, 128GB 8GB RAM',
                'battery' => 'Li-Po 5000 mAh, non-removable',
                'description' => 'Infinix Note 11 Pro is a slim, lightweight, and powerful Smartphone designed for the Apple iPhone. It features a 13.5-inch Super Retina XDR OLED display with HDR10 support, a 12MP primary camera, and a 7MP front camera. It has a 3.5mm headphone jack and a built-in microphone. It has a 128GB or 256GB storage option, and a 4GB or 8GB RAM option.',
                'price' => '5000000',
                'stock' => '10',
                'release_date' => now(),
                'image' => 'images/product_infinix_05G.jpg',
            ],
            [
                'id' => 9,
                'brand_id' => 102,
                'name' => 'Infinix Note 11',
                'slug' => 'ini-adalah-slug',
                'dimensions' => '164.4 x 76.7 x 7.9 mm',
                'display' => 'AMOLED, 650 nits (peak)',
                'os' => 'Android 11, XOS 10',
                'chipset' => 'MediaTek Helio G88 (12nm)',
                'cpu' => 'Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)',
                'memory' => '64GB 4GB RAM, 128GB 4GB RAM, 128GB 6GB RAM',
                'battery' => 'Li-Po 5000 mAh, non-removable',
                'description' => 'Infinix Note 11 is a slim, lightweight, and powerful Smartphone designed for the Apple iPhone. It features a 13.5-inch Super Retina XDR OLED display with HDR10 support, a 12MP primary camera, and a 7MP front camera. It has a 3.5mm headphone jack and a built-in microphone. It has a 64GB or 256GB storage option, and a 4GB or 8GB RAM option.',
                'price' => '4000000',
                'stock' => '10',
                'release_date' => now(),
                'image' => 'images/product_infinix_hot10T.jpg',
            ],
        ]);
    }
}
